[runtime] Fix unknown command use-case handling

diff --git a/src/offenbach b/src/offenbach
--- a/src/offenbach
+++ b/src/offenbach
@@ -154,6 +154,19 @@ EOH
 }
 
 #
+# Check whether the given offenbach/composer command exists
+# @param $command The command name
+#
+_is_command(){
+    local c=$1
+    for f in migrate $(composer list --raw | awk '{ print $1; }' | xargs)
+    do
+        [ "$c" = "$f" ] && return 0
+    done
+    return 1
+}
+
+#
 # Print help message
 # Print offenbach specific command help if appropriate, fallback to composer help otherwise
 # @param $command The command name
@@ -327,6 +340,13 @@ do
 done
 
 set -- "${args[@]}"
+
+# If the queried command is unknown, exit with an error message
+if ! _is_command "$1"
+then
+    printf "Error: unknown %s command, exiting.\n" "$1"
+    exit 127
+fi
 
 # If a working dir was supplied, change dir for it
 [ -n "${cwd}" ] && _chdir ${cwd}
